/**
 * AUTO-VISUALS PROOFS (Phase 3, 2026-07-21) — the moment a SONG finishes, a
 * lyric video, an audio-reactive visualizer and 3-5 thumbnails are generated by
 * cheap ffmpeg/image EDITS off the EXISTING master audio + lyrics + cover, NEVER
 * a re-render, $0. This proves: the VERBATIM even-paced lyric paging (with the
 * HONEST "not karaoke sync" caveat), the thumbnail variant plan, the single-pass
 * argv construction (1080x1920 vertical + "afro" watermark), the fail-soft
 * batch, the auto-trigger wiring on song completion, and — when ffmpeg + the
 * Anton font are available — the real renders (ffprobe dims + audio + burned
 * watermark/lyrics on real pixels, real thumbnail images, partial batch survival).
 *
 * Offline by design (mirrors test-clips.ts): the CONSTRUCTION + PLANNER + SOURCE-
 * SCAN laws always run; the ffmpeg render legs run only when the binary answers,
 * and the drawtext legs additionally need the cached Anton font — each skip is
 * announced honestly, never a fake pass.
 */
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdir, mkdtemp, readFile, rm, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  buildLyricVideoArgs,
  buildVisualizerArgs,
  buildThumbnailArgs,
  buildPosterBrandFilters,
  ensureDisplayFont,
  ffmpegAvailable,
  probeDurationS,
  renderLyricVideo,
  renderVisualizer,
  renderThumbnails,
  resolveVisualGradient,
  runFfmpeg,
  VISUAL_HEIGHT,
  VISUAL_WIDTH,
  THUMB_HEIGHT,
  THUMB_WIDTH,
  WATERMARK_TEXT,
  WATERMARK_HEIGHT_RATIO,
  POSTER_MARK_TEXT,
  POSTER_MARK_HEIGHT_RATIO,
  type ThumbnailRenderRequest,
} from "../src/lib/ffmpeg";
import {
  parseLyricLines,
  planLyricPages,
  planThumbnailVariants,
  thumbnailText,
  wrapLyricLine,
} from "../src/lib/visuals-plan";

function run(
  command: string,
  args: string[]
): Promise<{ code: number | null; stdout: Buffer }> {
  return new Promise(resolve => {
    const child = spawn(command, args, {
      windowsHide: true,
      stdio: ["ignore", "pipe", "pipe"],
    });
    const out: Buffer[] = [];
    child.stdout.on("data", c => out.push(Buffer.from(c)));
    child.once("close", code => resolve({ code, stdout: Buffer.concat(out) }));
    child.once("error", () => resolve({ code: null, stdout: Buffer.alloc(0) }));
  });
}

/** ffprobe the first video stream's exact width x height. */
async function probeWH(path: string): Promise<{ w: number; h: number }> {
  const { code, stdout } = await run("ffprobe", [
    "-v", "error",
    "-select_streams", "v:0",
    "-show_entries", "stream=width,height",
    "-of", "csv=p=0", path,
  ]);
  assert.equal(code, 0, "ffprobe stream dims must succeed");
  const [w, h] = stdout.toString("utf8").trim().split(",").map(n => Number(n));
  return { w: w ?? 0, h: h ?? 0 };
}

/** Does the file carry an audio stream? (ffprobe a:0 codec_type). */
async function hasAudioStream(path: string): Promise<boolean> {
  const { code, stdout } = await run("ffprobe", [
    "-v", "error",
    "-select_streams", "a:0",
    "-show_entries", "stream=codec_type",
    "-of", "csv=p=0", path,
  ]);
  return code === 0 && /audio/.test(stdout.toString("utf8"));
}

/** Mean R/G/B of a cropped region of a STILL image (no -ss — a JPEG has one
 *  frame and seeking would discard it). */
async function imageMeanRgb(
  path: string,
  crop: { w: number; h: number; x: number; y: number }
): Promise<{ r: number; g: number; b: number; luma: number }> {
  const { code, stdout } = await run("ffmpeg", [
    "-hide_banner", "-loglevel", "error",
    "-i", path,
    "-vf", `crop=${crop.w}:${crop.h}:${crop.x}:${crop.y}`,
    "-f", "rawvideo", "-pix_fmt", "rgb24", "-",
  ]);
  assert.equal(code, 0, "image crop extraction must succeed");
  assert.ok(stdout.length >= 3, "image must have pixels");
  let r = 0, g = 0, b = 0;
  const pixels = Math.floor(stdout.length / 3);
  for (let i = 0; i < pixels; i++) {
    r += stdout[i * 3]!;
    g += stdout[i * 3 + 1]!;
    b += stdout[i * 3 + 2]!;
  }
  r /= pixels; g /= pixels; b /= pixels;
  return { r, g, b, luma: 0.299 * r + 0.587 * g + 0.114 * b };
}

/** Mean R/G/B of ONE frame at time t (whole frame or a cropped region). */
async function frameMeanRgb(
  path: string,
  t: number,
  crop?: { w: number; h: number; x: number; y: number }
): Promise<{ r: number; g: number; b: number; luma: number }> {
  const vf = crop ? ["-vf", `crop=${crop.w}:${crop.h}:${crop.x}:${crop.y}`] : [];
  const { code, stdout } = await run("ffmpeg", [
    "-hide_banner", "-loglevel", "error",
    "-ss", t.toFixed(3), "-i", path,
    "-frames:v", "1", ...vf, "-f", "rawvideo", "-pix_fmt", "rgb24", "-",
  ]);
  assert.equal(code, 0, `frame extraction at ${t}s must succeed`);
  assert.ok(stdout.length >= 3, "frame must have pixels");
  let r = 0, g = 0, b = 0;
  const pixels = Math.floor(stdout.length / 3);
  for (let i = 0; i < pixels; i++) {
    r += stdout[i * 3]!;
    g += stdout[i * 3 + 1]!;
    b += stdout[i * 3 + 2]!;
  }
  r /= pixels; g /= pixels; b /= pixels;
  return { r, g, b, luma: 0.299 * r + 0.587 * g + 0.114 * b };
}

async function main() {
  // =====================================================================
  // A) CONSTRUCTION + PLANNER LAWS (pure — always run, no ffmpeg needed)
  // =====================================================================

  // --- VERBATIM lyric parsing: keep words, drop section markers/blanks -----
  {
    const body =
      "[Verse 1]\nI can't sleep, no\n\nOléku for the weekend\n[Hook]\nWe dey ball, we dey ball";
    const lines = parseLyricLines(body);
    assert.deepEqual(
      lines,
      ["I can't sleep, no", "Oléku for the weekend", "We dey ball, we dey ball"],
      "verbatim lyric lines kept EXACTLY; [Verse]/[Hook] markers + blanks dropped"
    );
    assert.deepEqual(parseLyricLines(null), [], "no body → no lines (an instrumental)");
    assert.deepEqual(parseLyricLines("[Intro]\n[Outro]"), [], "only markers → no lyric lines");
    console.log("[plan] parseLyricLines keeps words verbatim, drops [section] markers + blanks");
  }

  // --- wrapLyricLine wraps a long line WITHOUT losing any word -------------
  {
    const wrapped = wrapLyricLine("the whole city singing every single word tonight", 20);
    assert.ok(wrapped.length >= 2, "a long line wraps to multiple display lines");
    assert.ok(wrapped.every(l => l.length <= 24), "each display line respects the width");
    assert.equal(
      wrapped.join(" "),
      "the whole city singing every single word tonight",
      "every word survives the wrap (verbatim — nothing dropped)"
    );
    console.log("[plan] wrapLyricLine wraps long lines but never drops a word");
  }

  // --- EVEN-PACED paging tiles the WHOLE song (honest timing, not sync) ----
  {
    const body = Array.from({ length: 12 }, (_, i) => `line ${i + 1}`).join("\n");
    const plan = planLyricPages({ body, totalDurationS: 120, linesPerPage: 4 });
    assert.equal(plan.lineCount, 12, "all 12 verbatim lines paged");
    assert.equal(plan.pages.length, 3, "12 lines / 4 per page = 3 pages");
    assert.equal(plan.timing, "even-paced", "timing is honestly reported as even-paced");
    // Windows tile the whole song end-to-end with no gaps/overlaps.
    assert.equal(plan.pages[0]!.startS, 0, "first page starts at 0");
    assert.ok(Math.abs(plan.pages[0]!.endS - 40) < 0.01, "page 1 ends at duration/pages = 40s");
    assert.ok(Math.abs(plan.pages[1]!.startS - 40) < 0.01, "page 2 begins where page 1 ended");
    assert.equal(plan.pages[2]!.endS, 120, "the last page runs to the very end (no trailing blank)");
    // VERBATIM: the paged text is the exact source lines.
    assert.ok(plan.pages[0]!.text.includes("line 1") && plan.pages[0]!.text.includes("line 4"), "page 1 holds its 4 verbatim lines");
    const instrumental = planLyricPages({ body: "[Intro]\n[Outro]", totalDurationS: 90 });
    assert.equal(instrumental.pages.length, 0, "an instrumental yields 0 pages → NO lyric video (visualizer carries it)");
    console.log("[plan] planLyricPages tiles the whole song on a fixed cadence (even-paced, NOT karaoke sync) — verbatim");
  }

  // --- THUMBNAIL variants: 3-5, clean-cover included, hook option ----------
  {
    const variants = planThumbnailVariants({ title: "Oléku", hook: "We dey ball tonight" });
    assert.ok(variants.length >= 3 && variants.length <= 5, `3-5 thumbnail options (got ${variants.length})`);
    assert.ok(variants.some(v => v.textPos === "none" && v.text === ""), "a text-free clean-cover variant is always offered");
    assert.ok(variants.some(v => v.text === "We dey ball tonight"), "one variant carries the HOOK line");
    assert.ok(variants.some(v => v.text === "Oléku"), "title-forward variants use the title");
    assert.ok(variants.some(v => v.accent), "at least one variant carries a colored accent for punch");
    // Hook equal to the title collapses (no duplicate line) → falls back to title.
    const dupe = planThumbnailVariants({ title: "Same", hook: "same" });
    assert.ok(dupe.every(v => v.text === "Same" || v.text === ""), "a hook identical to the title collapses to the title");
    assert.equal(thumbnailText("   a very very very very very very long title indeed   ", 20).length <= 20, true, "thumbnailText trims to a word boundary");
    console.log("[plan] planThumbnailVariants: 3-5 options, clean-cover + hook + accent, dedupes hook==title");
  }

  // --- LYRIC VIDEO argv: 1080x1920, audio, ken-burns cover, paged text, wm -
  {
    const args = buildLyricVideoArgs({
      output: "/tmp/lyric.mp4",
      audioPath: "/tmp/audio.wav",
      fontPath: "C:/fonts/anton.ttf",
      coverPath: "C:/tmp/cover.png",
      gradient: resolveVisualGradient("afrobeats"),
      pageTextPaths: ["C:/tmp/p0.txt", "C:/tmp/p1.txt"],
      pageWindows: [
        { startS: 0, endS: 30 },
        { startS: 30, endS: 60 },
      ],
      watermarkTextPath: "C:/tmp/afro.txt",
      durationS: 60,
    });
    // Two inputs: the looped cover + the master audio, mapped to one output each.
    assert.equal(args.filter(a => a === "-i").length, 2, "exactly the cover + the master audio (one edit, no re-render)");
    assert.ok(args.includes("-loop") && args.includes("1"), "the cover is looped for the whole song");
    const fc = args[args.indexOf("-filter_complex") + 1]!;
    assert.ok(/\[1:a\]atrim/.test(fc), "the MASTER AUDIO drives the video (mapped + faded)");
    assert.ok(/zoompan=/.test(fc), "the cover gets a ken-burns zoom");
    assert.ok(/s=1080x1920/.test(fc), "ken-burns renders the 1080x1920 vertical frame");
    // EVEN-PACED page windows are burned as enable ranges — one per page (the
    // decimal-formatted windows; the watermark's own 0-3s window is separate).
    assert.equal((fc.match(/enable='between\(t,\d+\.\d{3},\d+\.\d{3}\)'/g) ?? []).length, 2, "one enable window per page (evenly paced)");
    assert.ok(/between\(t,0\.000,30\.000\)/.test(fc) && /between\(t,30\.000,60\.000\)/.test(fc), "the page windows tile the song");
    assert.ok(/x=W-text_w-/.test(fc), "the persistent 'afro' watermark drawtext is in the SAME pass");
    assert.equal(WATERMARK_TEXT, "afro", "the wordmark is 'afro'");
    assert.ok(args.includes("libx264") && args.includes("-crf") && args.includes("19"), "uses the ASSEMBLY_ENCODE preset");
    assert.ok(args.includes("+faststart"), "faststart for instant social playback");
    // NO-COVER path → a gradient backdrop, no zoompan.
    const grad = buildLyricVideoArgs({
      output: "/tmp/l.mp4", audioPath: "/tmp/a.wav", fontPath: "C:/f.ttf",
      coverPath: null, gradient: resolveVisualGradient("amapiano"),
      pageTextPaths: ["C:/p.txt"], pageWindows: [{ startS: 0, endS: 10 }],
      watermarkTextPath: "C:/w.txt", durationS: 10,
    });
    assert.ok(grad.some(a => /gradients=s=1080x1920/.test(a)), "no cover → the genre gradient backdrop (1080x1920)");
    assert.ok(!grad.some(a => /gradients=/.test(a) && false), "gradient path present");
    console.log("[lyric] buildLyricVideoArgs: cover+audio inputs, ken-burns→1080x1920, per-page enable windows, 'afro' watermark, ASSEMBLY_ENCODE");
  }

  // --- VISUALIZER argv: 1080x1920, audio-reactive showwaves over cover -----
  {
    const args = buildVisualizerArgs({
      output: "/tmp/viz.mp4",
      audioPath: "/tmp/audio.wav",
      fontPath: "C:/fonts/anton.ttf",
      coverPath: "C:/tmp/cover.png",
      gradient: resolveVisualGradient("afro_fusion"),
      watermarkTextPath: "C:/tmp/afro.txt",
      durationS: 30,
    });
    assert.equal(args.filter(a => a === "-i").length, 2, "cover + master audio, single edit");
    const fc = args[args.indexOf("-filter_complex") + 1]!;
    assert.ok(/\[1:a\]asplit=2/.test(fc), "the audio is split — one copy drives the visual, one is the output track");
    assert.ok(/showwaves=s=1080x1920/.test(fc), "an audio-reactive showwaves waveform at 1080x1920");
    assert.ok(/lumakey/.test(fc) && /overlay=/.test(fc), "the waveform is keyed onto the cover (cover color preserved)");
    assert.ok(/x=W-text_w-/.test(fc), "the 'afro' watermark rides the visualizer too");
    assert.ok(args.includes("libx264") && args.includes("+faststart"), "ASSEMBLY_ENCODE + faststart");
    console.log("[viz] buildVisualizerArgs: showwaves→1080x1920 over the cover (lumakey/overlay), audio split, 'afro' watermark");
  }

  // --- THUMBNAIL argv: 1280x720 still, cover crop + title + wordmark -------
  {
    const args = buildThumbnailArgs({
      output: "/tmp/t.jpg",
      coverPath: "C:/tmp/cover.png",
      gradient: resolveVisualGradient("afrobeats"),
      fontPath: "C:/fonts/anton.ttf",
      titleTextPath: "C:/tmp/title.txt",
      watermarkTextPath: "C:/tmp/afro.txt",
      crop: "center",
      textPos: "bottom",
      accent: false,
    });
    assert.equal(args.filter(a => a === "-i").length, 1, "one input (the cover) — an image edit");
    assert.ok(args.includes("-frames:v") && args[args.indexOf("-frames:v") + 1] === "1", "outputs ONE still frame");
    const vf = args[args.indexOf("-vf") + 1]!;
    assert.ok(/scale=1280:720/.test(vf) && /crop=1280:720/.test(vf), "cropped/scaled to the 1280x720 CTR still");
    assert.ok(/drawtext=.*title\.txt/.test(vf), "the bold title overlay is burned");
    assert.ok(/x=W-text_w-/.test(vf), "the small 'afro' wordmark bottom-right");
    assert.ok(args.includes("-q:v"), "encoded as a quality JPEG");
    // Clean-cover variant → no title band/drawtext (only the wordmark).
    const clean = buildThumbnailArgs({
      output: "/tmp/c.jpg", coverPath: "C:/cover.png", gradient: resolveVisualGradient("x"),
      fontPath: "C:/f.ttf", titleTextPath: null, watermarkTextPath: "C:/w.txt",
      crop: "center", textPos: "none", accent: false,
    });
    const cvf = clean[clean.indexOf("-vf") + 1]!;
    assert.equal((cvf.match(/drawtext=/g) ?? []).length, 1, "clean-cover variant carries ONLY the wordmark drawtext");
    console.log("[thumb] buildThumbnailArgs: single image edit → 1280x720 still, title+wordmark, clean-cover has wordmark only");
  }

  // --- BRANDED POSTER MARK: the big VEVO-style "AFRO" on the still ----------
  {
    // The pure poster-mark builder: one big bottom-left drawtext, from a textfile.
    const marks = buildPosterBrandFilters({
      fontPath: "C:/fonts/anton.ttf",
      textPath: "C:/tmp/afro.txt",
      width: THUMB_WIDTH,
      height: THUMB_HEIGHT,
    });
    assert.equal(marks.length, 1, "the poster mark is a single drawtext (the brand, not clutter)");
    const mark = marks[0]!;
    assert.ok(/textfile='[^']*afro\.txt'/.test(mark), "the mark text rides a textfile (escaping can never break the filter)");
    const markSize = Math.round(THUMB_HEIGHT * POSTER_MARK_HEIGHT_RATIO);
    assert.ok(new RegExp(`fontsize=${markSize}`).test(mark), `the mark is ~${(POSTER_MARK_HEIGHT_RATIO * 100).toFixed(0)}% frame height (fontsize ${markSize})`);
    // VEVO-style bottom-LEFT (x is the small margin, not W-text_w-*), and BIGGER
    // than the in-video watermark (POSTER_MARK vs WATERMARK height ratio).
    assert.ok(/:x=\d+:y=H-text_h-\d+/.test(mark), "the mark sits bottom-LEFT (not the watermark's bottom-right)");
    assert.ok(POSTER_MARK_HEIGHT_RATIO > WATERMARK_HEIGHT_RATIO * 1.5, `the poster mark (${POSTER_MARK_HEIGHT_RATIO}) is far bigger than the in-video watermark (${WATERMARK_HEIGHT_RATIO})`);
    assert.ok(POSTER_MARK_HEIGHT_RATIO >= 0.09 && POSTER_MARK_HEIGHT_RATIO <= 0.12, "the poster mark height is in the VEVO band (~9–12%)");
    assert.ok(/fontcolor=white/.test(mark) && /shadowcolor=/.test(mark), "white + drop shadow so it reads over any cover");
    assert.equal(POSTER_MARK_TEXT, "AFRO", "the poster mark says AFRO — the same identity as the 'afro' watermark, bigger");

    // buildThumbnailArgs({ poster: true }) → the big mark, NO title band/text.
    const posterArgs = buildThumbnailArgs({
      output: "/tmp/poster.jpg",
      coverPath: "C:/tmp/cover.png",
      gradient: resolveVisualGradient("afrobeats"),
      fontPath: "C:/fonts/anton.ttf",
      titleTextPath: "C:/tmp/title.txt", // supplied, but a poster must ignore it
      watermarkTextPath: "C:/tmp/afro.txt",
      crop: "center",
      textPos: "bottom",
      accent: true,
      poster: true,
    });
    assert.equal(posterArgs.filter(a => a === "-i").length, 1, "the poster is a single cover image edit");
    assert.ok(posterArgs.includes("-frames:v"), "the poster outputs ONE still frame");
    const pvf = posterArgs[posterArgs.indexOf("-vf") + 1]!;
    assert.equal((pvf.match(/drawtext=/g) ?? []).length, 1, "the poster carries ONLY the brand mark — no title, no small wordmark");
    assert.ok(!/title\.txt/.test(pvf), "the poster ignores the title (clean cover + brand, no clutter)");
    assert.ok(new RegExp(`fontsize=${markSize}`).test(pvf), "the poster's mark is the big VEVO-size mark");
    // The poster mark is bigger than a NORMAL thumbnail's small bottom-right wordmark.
    const normalArgs = buildThumbnailArgs({
      output: "/tmp/n.jpg", coverPath: "C:/tmp/cover.png", gradient: resolveVisualGradient("afrobeats"),
      fontPath: "C:/fonts/anton.ttf", titleTextPath: null, watermarkTextPath: "C:/tmp/afro.txt",
      crop: "center", textPos: "none", accent: false,
    });
    const nvf = normalArgs[normalArgs.indexOf("-vf") + 1]!;
    const posterFont = Number(pvf.match(/fontsize=(\d+)/)![1]);
    const normalFont = Number(nvf.match(/fontsize=(\d+)/)![1]);
    assert.ok(posterFont > normalFont, `the poster mark (${posterFont}px) is bigger than a normal thumbnail's wordmark (${normalFont}px)`);
    console.log(`[poster] buildPosterBrandFilters: one big bottom-left AFRO mark (${posterFont}px vs the ${normalFont}px watermark), poster thumbnail is clean cover + brand only`);
  }

  // --- PRIMARY POSTER designation: exactly one, always produced ------------
  {
    for (const count of [3, 4, 5]) {
      const variants = planThumbnailVariants({ title: "Oléku", hook: "We dey ball tonight", count });
      const posters = variants.filter(v => v.poster);
      assert.equal(posters.length, 1, `count=${count}: exactly ONE branded poster is planned`);
      const poster = posters[0]!;
      assert.ok(poster.text === "" && poster.textPos === "none", "the branded poster is a clean cover (no title clutter)");
      assert.ok(variants.some(v => !v.poster && v.text), `count=${count}: the titled CTR thumbnails are kept too`);
    }
    // The poster survives even the smallest set — it is never sliced off.
    const three = planThumbnailVariants({ title: "T", count: 3 });
    assert.ok(three.some(v => v.poster), "the branded poster is ALWAYS included, even at the minimum count");
    console.log("[poster] planThumbnailVariants: exactly one branded poster, always produced (never sliced), titled CTR variants kept");
  }

  // =====================================================================
  // B) SOURCE-SCAN LAWS — the auto-trigger + mirror + registration (pure)
  // =====================================================================
  {
    for (const [file, reason] of [
      ["src/processors/own-engine.ts", "song-rendered"],
      ["src/processors/music.ts", "song-mastered"],
      ["src/processors/master.ts", "song-mastered"],
      ["src/processors/produce.ts", "song-demo"],
    ] as const) {
      const src = await readFile(file, "utf8");
      assert.ok(/enqueueGenerateVisuals\(/.test(src), `${file} fires the visuals build on song completion`);
      assert.ok(src.includes(reason), `${file} tags the completion reason (${reason})`);
    }

    const lib = await readFile("src/lib/visuals.ts", "utf8");
    assert.ok(/await import\('\.\/enqueue'\)/.test(lib), "visuals.ts lazy-imports ./enqueue (no eager Redis handle), mirroring clips/release-kit");
    assert.ok(/jobId:\s*`\$\{VISUALS_JOB\}-\$\{payload\.songId\}/.test(lib), "dedupes concurrent completions by the song id");
    assert.ok(/catch\s*\(err\)[\s\S]{0,200}render unaffected/.test(lib), "enqueue is FAIL-SOFT — a visuals problem never fails the render");
    assert.ok(/visualsStatus:\s*'creating'/.test(lib), "flips the song to 'creating' so the tab can say so");

    const idx = await readFile("src/index.ts", "utf8");
    assert.ok(/makeWorker\("visuals"/.test(idx), "index registers the dedicated 'visuals' lane");
    assert.ok(/processGenerateVisuals\(/.test(idx), "the visuals lane dispatches to processGenerateVisuals");

    const proc = await readFile("src/processors/generate-visuals.ts", "utf8");
    assert.ok(/songVisual\.count\(/.test(proc) && /!p\.force/.test(proc), "processor is idempotent (skips a song that already has visuals unless forced)");
    assert.ok(/renderLyricVideo\(/.test(proc) && /renderVisualizer\(/.test(proc) && /renderThumbnails\(/.test(proc), "processor builds all three assets");
    assert.ok(/deleteMany\(\{\s*where:\s*\{\s*songId:\s*p\.songId\s*\}\s*\}\)/.test(proc), "a forced regenerate replaces the old set");
    assert.ok(/costUsd:\s*0/.test(proc), "visuals are charged $0 (ffmpeg/image edits off the master)");
    assert.ok(/timingCaveat/.test(proc), "the lyric video meta states the HONEST even-paced (not karaoke) timing caveat");
    // Each asset in its OWN try/catch — one failing never kills the others.
    assert.ok((proc.match(/batch continues/g) ?? []).length >= 2, "each asset fails soft independently (batch continues)");

    // BRANDED POSTER wiring: the processor pins the poster + marks it in meta,
    // fail-soft (a poster problem never fails the visuals build).
    assert.ok(/poster:\s*v\.poster/.test(proc), "the poster variant flows into the thumbnail render request");
    assert.ok(/poster:\s*!!thumb\.request\.poster/.test(proc), "the stored thumbnail carries meta.poster (the before-play still is findable)");
    assert.ok(/if\s*\(thumb\.request\.poster\)\s*posterUrl\s*=\s*url/.test(proc), "the branded poster's canonical url is captured");
    assert.ok(/data:\s*\{\s*posterUrl\s*\}/.test(proc) && /\.catch\(\(\)\s*=>\s*undefined\)/.test(proc), "Song.posterUrl is pinned fail-soft (missing poster → falls back to the cover)");

    // The release payload + page + social seam all reach for the branded poster.
    const pub = await readFile("../api/src/routes/public.ts", "utf8");
    assert.ok(/song\.posterUrl\s*\?\?\s*posterVisualRef/.test(pub), "the release payload resolves the pinned poster (legacy fallback to the poster thumbnail)");
    assert.ok(/posterUrl:\s*posterUrl\s*\?\?\s*coverUrl/.test(pub), "the release payload returns the branded poster (cover fallback)");
    const page = await readFile("../web/app/r/[id]/page.tsx", "utf8");
    assert.ok(/const\s+ogImage\s*=\s*r\.posterUrl\s*\?\?\s*r\.coverUrl/.test(page), "the OG/Twitter image is the branded poster (cover fallback) — shared links preview with the AFRO brand");
    assert.ok(/const\s+videoPoster\s*=\s*r\.posterUrl\s*\?\?\s*r\.coverUrl/.test(page), "the video's poster attribute is the branded poster");
    const socShared = await readFile("../../packages/shared/src/social-distribution.ts", "utf8");
    assert.ok(/posterUrl:\s*input\.posterUrl\s*\?\?\s*null/.test(socShared), "every built social post carries the branded poster");
    const socPub = await readFile("src/processors/social-publish.ts", "utf8");
    assert.ok(/posterUrl,/.test(socPub) && /song\.posterUrl/.test(socPub), "the publish job resolves + passes the branded poster to the post builder");

    console.log("[wire] own-engine/music/master/produce → enqueueGenerateVisuals, visuals.ts mirrors clips, visuals lane registered, processor idempotent + $0 + honest caveat; branded poster pinned (fail-soft) → OG image + video poster + social posts");
  }

  // =====================================================================
  // C) FFMPEG RENDER LEGS (need the binary; drawtext also needs the font)
  // =====================================================================
  if (!(await ffmpegAvailable())) {
    console.log(
      "[visuals] SKIP render legs honestly: ffmpeg not on this host " +
        "(runs in the worker image; construction + planner + wiring proven above)"
    );
    console.log("test-visuals: PASS (construction-only)");
    return;
  }
  const fontPath = await ensureDisplayFont();
  if (!fontPath) {
    console.log("[visuals] SKIP render legs honestly: Anton font unavailable offline (construction + wiring proven above)");
    console.log("test-visuals: PASS (construction-only)");
    return;
  }

  const dir = await mkdtemp(join(tmpdir(), "visuals-"));
  try {
    // Synthetic inputs: a 3s stereo tone (the "master audio") + a tiny dark
    // cover PNG. Cheap, deterministic, no network.
    const audioPath = join(dir, "audio.wav");
    await runFfmpeg([
      "-f", "lavfi", "-i", "sine=frequency=330:duration=3",
      "-ac", "2", "-ar", "44100", audioPath,
    ]);
    assert.ok((await stat(audioPath)).size > 1000, "synthetic master audio rendered");
    assert.ok(Math.abs((await probeDurationS(audioPath)) - 3) < 0.6, "audio probes ~3s");

    const coverPath = join(dir, "cover.png");
    await runFfmpeg([
      "-f", "lavfi", "-i", "color=c=0x101822:s=512x512", "-frames:v", "1", coverPath,
    ]);
    assert.ok((await stat(coverPath)).size > 200, "synthetic dark cover rendered");

    // ---- C1) LYRIC VIDEO over the GRADIENT (dark → the watermark + lyrics
    //          read as bright pixels): 1080x1920, has audio, burned text ----
    const lyricPlan = planLyricPages({
      body: "We dey ball tonight\nEvery single word",
      totalDurationS: 3,
      linesPerPage: 2,
    });
    assert.ok(lyricPlan.pages.length >= 1, "the lyric planner produced at least one page");
    const lyricVid = join(dir, "lyric.mp4");
    await renderLyricVideo({
      output: lyricVid,
      audioPath,
      fontPath,
      coverPath: null, // dark gradient → clean corners for the pixel proofs
      gradient: resolveVisualGradient("afrobeats"),
      pages: lyricPlan.pages,
      durationS: 3,
    });
    const lyricWH = await probeWH(lyricVid);
    assert.deepEqual(lyricWH, { w: VISUAL_WIDTH, h: VISUAL_HEIGHT }, `lyric video is 1080x1920 (got ${lyricWH.w}x${lyricWH.h})`);
    assert.ok(await hasAudioStream(lyricVid), "the lyric video carries the MASTER AUDIO stream");
    assert.ok(Math.abs((await probeDurationS(lyricVid)) - 3) < 0.6, "lyric video runs the song length (~3s)");
    // The 'afro' watermark lights the bottom-right over the dark gradient.
    const wm = await frameMeanRgb(lyricVid, 1.4, { w: 240, h: 110, x: 800, y: 1780 });
    assert.ok(wm.luma > 1.0, `the 'afro' watermark is burned bottom-right (luma ${wm.luma.toFixed(2)})`);
    // The verbatim lyric page lights the frame center during its window.
    const mid = await frameMeanRgb(lyricVid, 1.4, { w: 700, h: 300, x: 190, y: 810 });
    assert.ok(mid.luma > 1.5, `the paged lyric text is burned center-frame (luma ${mid.luma.toFixed(2)})`);
    assert.ok((await stat(lyricVid)).size > 2000, "the lyric video is a real non-empty mp4");
    console.log("[lyric] rendered 1080x1920 lyric video: master audio stream + burned lyrics + 'afro' watermark on real pixels");

    // ---- C1b) LYRIC VIDEO over a real COVER (ken-burns) still 1080x1920 ---
    const lyricCover = join(dir, "lyric-cover.mp4");
    await renderLyricVideo({
      output: lyricCover, audioPath, fontPath,
      coverPath, gradient: resolveVisualGradient("afrobeats"),
      pages: lyricPlan.pages, durationS: 3,
    });
    assert.deepEqual(await probeWH(lyricCover), { w: VISUAL_WIDTH, h: VISUAL_HEIGHT }, "the ken-burns cover lyric video is also 1080x1920");
    console.log("[lyric] the ken-burns COVER path renders cleanly (zoompan) at 1080x1920");

    // ---- C2) VISUALIZER: a real audio-reactive 1080x1920 mp4 --------------
    const viz = join(dir, "viz.mp4");
    await renderVisualizer({
      output: viz, audioPath, fontPath,
      coverPath, gradient: resolveVisualGradient("amapiano"), durationS: 3,
    });
    const vizWH = await probeWH(viz);
    assert.deepEqual(vizWH, { w: VISUAL_WIDTH, h: VISUAL_HEIGHT }, `visualizer is 1080x1920 (got ${vizWH.w}x${vizWH.h})`);
    assert.ok(await hasAudioStream(viz), "the visualizer carries the master audio stream");
    // Audio-reactive: the showwaves waveform lights the centerline over the
    // darkened cover (the sine drives a visible white waveform).
    const band = await frameMeanRgb(viz, 1.5, { w: 1080, h: 120, x: 0, y: 900 });
    assert.ok(band.luma > 30, `the audio-reactive waveform is drawn across the frame (centerline luma ${band.luma.toFixed(1)})`);
    console.log("[viz] rendered a real audio-reactive 1080x1920 visualizer (showwaves centerline lit over the cover)");

    // ---- C3) THUMBNAILS: 3-5 real 1280x720 images, title burned + the poster ----
    const variants = planThumbnailVariants({ title: "Oléku", hook: "We dey ball tonight" });
    const requests: ThumbnailRenderRequest[] = variants.map(v => ({
      id: v.id, text: v.text, crop: v.crop, textPos: v.textPos, accent: v.accent, poster: v.poster,
    }));
    const good = await renderThumbnails({
      workDir: dir, coverPath, gradient: resolveVisualGradient("afrobeats"),
      fontPath, requests, width: THUMB_WIDTH, height: THUMB_HEIGHT,
    });
    assert.ok(good.ok.length >= 3 && good.ok.length <= 5, `3-5 thumbnails produced (got ${good.ok.length})`);
    assert.equal(good.failed.length, 0, "every thumbnail rendered on a valid cover");
    for (const t of good.ok) {
      const wh = await probeWH(t.path);
      assert.deepEqual(wh, { w: THUMB_WIDTH, h: THUMB_HEIGHT }, `thumbnail ${t.id} is 1280x720 (got ${wh.w}x${wh.h})`);
      assert.ok((await stat(t.path)).size > 500, `thumbnail ${t.id} is a real non-empty image`);
    }
    // The bold title band lights up over the dark cover on a titled variant.
    const titled = good.ok.find(t => t.request.textPos === "bottom" && !t.request.poster);
    if (titled) {
      const band = await imageMeanRgb(titled.path, { w: 900, h: 140, x: 190, y: 560 });
      assert.ok(band.luma > 15, `the thumbnail title is burned in (band luma ${band.luma.toFixed(1)})`);
    }
    // ---- C3b) THE BRANDED POSTER: the big "AFRO" mark lit bottom-LEFT ------
    const poster = good.ok.find(t => t.request.poster);
    assert.ok(poster, "the branded poster thumbnail was produced");
    // The white AFRO mark lights the bottom-LEFT over the dark cover, while the
    // bottom-RIGHT (no small wordmark on a poster) stays the dark cover — proof
    // the mark is present, prominent, and VEVO-positioned left.
    const markL = await imageMeanRgb(poster!.path, { w: 260, h: 110, x: 58, y: 560 });
    const cornerR = await imageMeanRgb(poster!.path, { w: 260, h: 110, x: 962, y: 560 });
    assert.ok(markL.luma > 35, `the big AFRO poster mark is burned bottom-left (mark luma ${markL.luma.toFixed(1)})`);
    assert.ok(markL.luma > cornerR.luma + 8, `the mark is bottom-LEFT (left ${markL.luma.toFixed(1)} > right ${cornerR.luma.toFixed(1)}), not the watermark's bottom-right`);
    // The poster is a CLEAN cover: no title band mid-frame like the CTR variants.
    console.log(`[poster] rendered the branded poster still: big AFRO mark lit bottom-left (luma ${markL.luma.toFixed(1)} vs right ${cornerR.luma.toFixed(1)}) — clean cover, no title clutter`);
    console.log(`[thumb] rendered ${good.ok.length} real 1280x720 thumbnail images (title burned + the branded poster)`);

    // ---- C4) FAIL-SOFT BATCH: one asset errors, the batch returns the rest.
    // Pre-create a DIRECTORY at exactly one thumbnail's output path so that ONE
    // ffmpeg write fails while the others still succeed — a real partial failure.
    const dir2 = await mkdtemp(join(tmpdir(), "visuals-fail-"));
    try {
      const poisonIndex = 2;
      const poisonId = requests[poisonIndex]!.id;
      await mkdir(join(dir2, `thumb-${poisonIndex}-${poisonId}.jpg`)); // a dir where ffmpeg wants a file
      const mixed = await renderThumbnails({
        workDir: dir2, coverPath, gradient: resolveVisualGradient("afrobeats"),
        fontPath, requests, width: THUMB_WIDTH, height: THUMB_HEIGHT,
      });
      assert.ok(mixed.failed.length >= 1, "the poisoned thumbnail failed");
      assert.ok(mixed.failed.some(f => f.id === poisonId), `the failure is the poisoned variant (${poisonId})`);
      assert.equal(
        mixed.ok.length,
        requests.length - mixed.failed.length,
        "FAIL-SOFT: the batch still returns every OTHER thumbnail (one error never kills the rest)"
      );
      assert.ok(mixed.ok.length >= 3, "the surviving thumbnails still make a full set");
      console.log(`[thumb] FAIL-SOFT batch: 1 poisoned render failed, the other ${mixed.ok.length} still came back (no throw)`);
    } finally {
      await rm(dir2, { recursive: true, force: true }).catch(() => {});
    }

    // ---- C4b) THE POSTER ITSELF is fail-soft: poison the branded poster and
    //           the rest of the set still comes back — poster branding NEVER
    //           fails the visuals build (the processor just leaves posterUrl null).
    {
      const posterIdx = requests.findIndex(r => r.poster);
      assert.ok(posterIdx >= 0, "the branded poster is in the request set");
      const dir3 = await mkdtemp(join(tmpdir(), "visuals-poster-fail-"));
      try {
        await mkdir(join(dir3, `thumb-${posterIdx}-${requests[posterIdx]!.id}.jpg`));
        const mixed = await renderThumbnails({
          workDir: dir3, coverPath, gradient: resolveVisualGradient("afrobeats"),
          fontPath, requests, width: THUMB_WIDTH, height: THUMB_HEIGHT,
        });
        assert.ok(mixed.failed.some(f => f.id === requests[posterIdx]!.id), "the poisoned POSTER failed (isolated)");
        assert.ok(!mixed.ok.some(t => t.request.poster), "no poster came back from the poisoned run");
        assert.ok(mixed.ok.length >= 3, "FAIL-SOFT: a poster failure never kills the other thumbnails");
        console.log("[poster] FAIL-SOFT: the poster render failing leaves the rest intact (poster branding never fails the build)");
      } finally {
        await rm(dir3, { recursive: true, force: true }).catch(() => {});
      }
    }

    console.log("test-visuals: PASS");
  } finally {
    await rm(dir, { recursive: true, force: true }).catch(() => {});
  }
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
